name: CI - FinTrack-Pro

# Ejecutar el workflow cuando haya un push o un pull request en las ramas main y develop
on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  build-and-test:
    name: Build and Test iOS Project
    runs-on: macos-latest

    steps:
      # Paso 1: Checkout del código del repositorio
      - name: Checkout source code
        uses: actions/checkout@v2
      
      # Paso 2: Configurar Xcode
      - name: Set up Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: "14.0"  # Especifica la versión de Xcode que necesitas

      # Paso 3: Instalar dependencias con Swift Package Manager
      - name: Resolve Swift Package Dependencies
        run: swift package resolve

      # Paso 4: Compilar el proyecto
      - name: Build the project
        run: xcodebuild -scheme "FinTrackPro" -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 14,OS=16.0' build | xcpretty

      # Paso 5: Ejecutar pruebas unitarias
      - name: Run Unit Tests
        run: xcodebuild test -scheme "FinTrackPro" -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 14,OS=16.0' -enableCodeCoverage YES | xcpretty